name: headmodelling
channels:
  - conda-forge
  - defaults
dependencies:
  - ipympl=0.9.3
  - ipython=8.14.0
  - matplotlib=3.7.2
  - meshio=5.3.4
  - notebook=7.0.2
  - numpy=1.25.2
  - pandas=2.0.3
  - pyntcloud=0.3.1
  - python=3.10.12
  - scikit-learn=1.3.0
  - scipy=1.11.2
